
[[Foliage]]
model = "Cube"
name = "pCube1"
translation = [0.000000, 0.000000, 1.884432]

[[Foliage]]
model = "Cube"
name = "pCube2"
translation = [-2.162443, 0.785289, 1.884432]

[[Foliage]]
model = "Cube"
name = "pCube5"
translation = [1.0, 0.0, 1.0]

[[Foliage]]
model = "Cube"
name = "pCube3"
rotation = [0.301642, -0.213252, 0.069416, 0.926670]
translation = [1.786722, 0.785289, -2.705321]

[[Static]]
model = "Sphere"
name = "pSphere1"
scale = [0.535201, 0.535201, 0.535201]
translation = [0.000000, 1.219372, -3.369186]

[[Static]]
model = "Sphere"
name = "pSphere2"
translation = [-2.0, 0.000000, 0.000000]

[[Static]]
model = "Sphere"
name = "pSphere3"
scale = [0.535201, 0.535201, 0.535201]
translation = [-3.344349, -0.868624, -2.903498]
